### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by tilsche**
While I tried to build FastGlobalFileStatus for STAT, I ran across a number of build issues which I fixed. There are only so many file changes because files generated by autotools are under version control.

### CODE REVIEW

**Comment by dongahn** [comment]
@tilsche: Thank you for the PR. Let me warn that FastGlobalFileStatus is work in progress and you will find various issues.

Several things will help me review your PR.
- Please create an issue to details the environments you are having issues and refer that issue in the PR.
- Split commits into multiple ones that can be topically grouped. E.g., configure.ac can go to one commit. Makefile.am's can go to another. Generated files can go to other separate commits, which I will pay almost no attention. I see your comment on the generated files. There are different schools of thoughts there. I'm thinking perhaps I should drop the generated files and have the developers always run bootstrap... 
- Provide commit messages with some level of details.

BTW, I'm not familiar with your github id. Have we or somebody in the STAT team been working together before?

**Comment by tilsche** [comment]
@dongahn, sorry for the lack of context of the PR, I wanted to get it out before leaving work. I will improve it tomorrow. I think with some more context all changes are quite trivial.

The generated files are indeed a bit annoying, I guess the commit split mitigates it a bit. I understand it is a choice of two evil considering the alternative requires anyone who wants to clone & build to also have specific autotools versions. Also my animosity towards autotools unfortunately doesn't imply that there are good alternatives. But I didn't come here to rant - just to help fix a few small bugs ;).

I have first heard of STAT from Martin Schulz whom I met on a few occasions. Unfortunately couldn't use it so far because it is not yet installed at my site (TU Dresden). From the STAT documentation I assumed that FastGlobalFileStatus was basically essential for a really scalable STAT usage on a parallel file system.

**Comment by dongahn** [comment]
@tilsche: Great. For other dependencies and how to integrate them with STAT, @lee218llnl should be resourceful. BTW, please take a look at [MPA](https://github.com/LLNL/MountPointAttributes) as well, which is the node-local engine that FGFS uses. TotalView and STAT are the main users of MPA.

I don't have whole lot of cycles to tend these scalable infrastructure modules. But I will help as much as I can. I think the area were we need most help at this point is to hook up the test cases to CI and populate more test cases through it. 

Look forward to seeing your amending "git push"

**Comment by tilsche** [comment]
I cleaned up the commits, hope you can now use them.

For the addressed errors see #2

**Comment by dongahn** [comment]
Nice! A minor nit. 

Can the (3rd commit )(https://github.com/tilsche/FastGlobalFileStatus/commit/07c6330a89e1bf40d1f68841eaeb6fa4949f3c49) and the final commit squashed?

You can use git rebase --interactive to do this easily.

**Comment by tilsche** [comment]
> Can the (3rd commit )(tilsche@07c6330) and the final commit squashed?

Done.

**Comment by dongahn** [comment]
Quick! After I get into my office i will give this another look. But it seems great at first glance. I was thinking perhaps last 3 commits can also be squashed so that each commit wont break. But until i will set up CI these details can be omitted. Thanks.

**Comment by dongahn** [comment]
Looks good to me. Thanks.

**Pull request merged**
